model:
  base_learning_rate: 2.0e-06
  target: ldm.model.latent_diffusion.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 16
    channels: 256
#    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.model.unet.UNetModel
      params:
        image_size: 16
        in_channels: 256
        out_channels: 256
        model_channels: 224
        attention_resolutions:
          # note: this isn\t actually the resolution but
          # the downsampling factor, i.e. this corresnponds to
          # attention on spatial resolution 8,16,32, as the
          # spatial reolution of the latents is 64 for f4
          - 8
          - 4
          - 2
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 3
          - 4
        num_head_channels: 32
    first_stage_config:
      target: vqgan.model.vqvae.VQModelInterface
      params:
        embed_dim: 256
        n_embed: 1024
        ckpt_path: logs/2025-07-10T20-51-55_autoencoder_FLIm/checkpoints/vqgan.ckpt
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__
data:
  target: datasets.data_utils.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 4
    wrap: false
    train:
      target: datasets.flim_dataset.FLImDataset
      params:
        size: 256
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/images_512x512/train"
        aug_p: 0.25
    validation:
      target: datasets.flim_dataset.FLImDataset
      params:
        size: 256
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/images_512x512/test"
        aug_p: 0.25


lightning:
  callbacks:
    image_logger:
      target: loggers.ImageLogger
      params:
        batch_frequency: 10000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    min_epochs: 10000
    max_epochs: 10000
