model:
  base_learning_rate: 4.5e-6
  # From: https://github.com/CompVis/taming-transformers/blob/3ba01b241669f5ade541ce990f7650a3b8f65318/configs/faceshq_vqgan.yaml
  target: vqgan.model.autoencoder.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: vqgan.data_utils.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: False
    train:
      target: vqgan.datasets.flim_dataset.FLImDataset
      params:
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/images_512x512/train"
        size: 256
    validation:
      target: vqgan.datasets.flim_dataset.FLImDataset
      params:
        root_dir: "/home/ataffe/SyntheticData/SyntheticDataGenForFLImViz/data/images_512x512/test"
        size: 256

lightning:
  callbacks:
    image_logger:
      target: vqgan.loggers.ImageLogger
      params:
        batch_frequency: 100
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    gpus: 1